plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
checks:
  similar-code:
    config:
      threshold: 75
exclude_patterns:
  - "**/__tests__/" # Tests
